-- Import brands into seo_brands
-- Run in Supabase SQL Editor

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (58, 'Ecologic', 'brandsecologic', '/brands/ecologic/', 'unknown'),
    (67, 'Ausganica', 'ausganica', '/ausganica/', 'unknown'),
    (68, 'Niugini Organics', 'brandsNiugini-Organics', '/brands/Niugini-Organics/', 'unknown'),
    (69, 'Dr Organic', 'dr-organic', '/dr-organic/', 'unknown'),
    (70, 'Every Bit Organic Raw', 'every-bit-organic', '/every-bit-organic/', 'unknown'),
    (73, 'Amazonia', 'amazonia', '/amazonia/', 'unknown'),
    (74, 'Aloe Dent', 'brandsAloe-Dent', '/brands/Aloe-Dent/', 'unknown'),
    (75, 'Alter Eco', 'brandsAlter-Eco', '/brands/Alter-Eco/', 'unknown'),
    (79, 'Barbadensis Gold', 'brandsBarbadensis-Gold', '/brands/Barbadensis-Gold/', 'unknown'),
    (80, 'Amber Love', 'amber-love', '/amber-love/', 'unknown'),
    (81, 'Auromere', 'brandsAuromere', '/brands/Auromere/', 'unknown'),
    (83, 'Amazing Oils', 'amazing-oils', '/amazing-oils/', 'unknown'),
    (84, 'Aloe Pura', 'brandsAloe-Pura', '/brands/Aloe-Pura/', 'unknown'),
    (87, 'Alchemy Cordials', 'brandsAlchemy-Cordials', '/brands/Alchemy-Cordials/', 'unknown'),
    (88, 'Ancient Minerals', 'brandsAncient-Minerals', '/brands/Ancient-Minerals/', 'unknown'),
    (89, 'Anna''s', 'brandsAnnas', '/brands/Annas/', 'unknown'),
    (91, 'Byron Chai', 'brandsByron-Chai', '/brands/Byron-Chai/', 'unknown'),
    (94, 'Bragg', 'bragg-live-food', '/bragg-live-food/', 'unknown'),
    (95, 'Bioastin', 'brandsBioastin', '/brands/Bioastin/', 'unknown'),
    (96, 'Burts Bees', 'burts-bees', '/burts-bees/', 'unknown'),
    (103, 'Book', 'brandsBook', '/brands/Book/', 'unknown'),
    (104, 'Breath Pearls', 'brandsBreath-Pearls', '/brands/Breath-Pearls/', 'unknown'),
    (106, 'Cellfood', 'brandsCellfood', '/brands/Cellfood/', 'unknown'),
    (107, 'Chai Tea', 'brandsChai-Tea', '/brands/Chai-Tea/', 'unknown'),
    (109, 'Cheeki', 'cheeki', '/cheeki/', 'unknown'),
    (115, 'Clif Bar', 'clif-bars-australia', '/clif-bars-australia/', 'unknown'),
    (118, 'Comvita', 'brandsComvita', '/brands/Comvita/', 'unknown'),
    (119, 'Cook Islands', 'brandsCook-Islands', '/brands/Cook-Islands/', 'unknown'),
    (120, 'Coombs Family Farms', 'brandsCoombs-Family-Farms', '/brands/Coombs-Family-Farms/', 'unknown'),
    (124, 'Dr Superfoods', 'dr-superfoods', '/dr-superfoods/', 'unknown'),
    (125, 'Dr Tung''s', 'brandsDr-Tungs', '/brands/Dr-Tungs/', 'unknown'),
    (133, 'Ecobud', 'brandsEcobud', '/brands/Ecobud/', 'unknown'),
    (135, 'Eden Health foods', 'eden-health-foods', '/eden-health-foods/', 'unknown'),
    (136, 'Egyptian Red', 'brandsEgyptian-Red', '/brands/Egyptian-Red/', 'unknown'),
    (138, 'Enviro Products', 'brandsEnviro-Products', '/brands/Enviro-Products/', 'unknown'),
    (141, 'Essential Oxygen', 'brandsEssential-Oxygen', '/brands/Essential-Oxygen/', 'unknown'),
    (142, 'Eucoclean', 'eucoclean', '/eucoclean/', 'unknown'),
    (151, 'Giovanni', 'giovanni-hair-care', '/giovanni-hair-care/', 'unknown'),
    (152, 'Go Bamboo', 'brandsGo-Bamboo', '/brands/Go-Bamboo/', 'unknown'),
    (153, 'Gold Mine', 'brandsGold-Mine', '/brands/Gold-Mine/', 'unknown'),
    (155, 'Green Nutritionals', 'green-nutritionals', '/green-nutritionals/', 'unknown'),
    (156, 'Hab Shifa', 'brandsHab-Shifa', '/brands/Hab-Shifa/', 'unknown'),
    (159, 'Harmony Soapworks', 'brandsHarmony-Soapworks', '/brands/Harmony-Soapworks/', 'unknown'),
    (160, 'Hemp Foods Australia', 'hemp-foods-australia', '/hemp-foods-australia/', 'unknown'),
    (164, 'Jack n'' Jill', 'jack-n-jill', '/jack-n-jill/', 'unknown'),
    (171, 'Kin Kin Naturals', 'kin-kin-naturals', '/kin-kin-naturals/', 'unknown'),
    (173, 'Kintra Foods', 'brandsKintra-Foods', '/brands/Kintra-Foods/', 'unknown'),
    (177, 'Lemon Myrtle Fragrances', 'brandsLemon-Myrtle-Fragrances', '/brands/Lemon-Myrtle-Fragrances/', 'unknown'),
    (179, 'Lotus', 'brandsLotus', '/brands/Lotus/', 'unknown'),
    (182, 'Maharishi Ayurveda', 'brandsMaharishi-Ayurveda', '/brands/Maharishi-Ayurveda/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (185, 'Montville Coffee', 'brandsMontville-Coffee', '/brands/Montville-Coffee/', 'unknown'),
    (187, 'Mt Retour', 'brandsMt-Retour', '/brands/Mt-Retour/', 'unknown'),
    (188, 'Nakula', 'brandsNakula', '/brands/Nakula/', 'unknown'),
    (190, 'NatraCare', 'brandsNatracare', '/brands/Natracare/', 'unknown'),
    (199, 'Naturally Sweet', 'brandsNaturally-Sweet', '/brands/Naturally-Sweet/', 'unknown'),
    (203, 'Nirvana Organics', 'brandsNirvana-Organics', '/brands/Nirvana-Organics/', 'unknown'),
    (206, 'NTS Health', 'nts-health', '/nts-health/', 'unknown'),
    (208, 'Nutribiotic', 'brandsNutribiotic', '/brands/Nutribiotic/', 'unknown'),
    (209, 'Nutri-herbal', 'brandsNutri-Leaf', '/brands/Nutri-Leaf/', 'unknown'),
    (219, 'Organic Times', 'brandsOrganic-Times', '/brands/Organic-Times/', 'unknown'),
    (222, 'Original Colloidal', 'brandsOriginal-Colloidal', '/brands/Original-Colloidal/', 'unknown'),
    (227, 'Planet Organic', 'planet-organic', '/planet-organic/', 'unknown'),
    (229, 'Power Super Foods', 'power-superfoods', '/power-superfoods/', 'unknown'),
    (230, 'PPC Herbs', 'brandsPPC-Herbs', '/brands/PPC-Herbs/', 'unknown'),
    (231, 'Primal Health Products', 'brandsPrimal-Health-Products', '/brands/Primal-Health-Products/', 'unknown'),
    (233, 'Pure Food Essentials', 'brandsPure-Food-Essentials', '/brands/Pure-Food-Essentials/', 'unknown'),
    (238, 'Rosehip Plus', 'brandsRosehip-Plus', '/brands/Rosehip-Plus/', 'unknown'),
    (239, 'Rose-hip Vital', 'brandsRose-Hip-Vital', '/brands/Rose-Hip-Vital/', 'unknown'),
    (241, 'Safix', 'brandsSafix', '/brands/Safix/', 'unknown'),
    (243, 'Salt of the Earth', 'brandsSalt-of-the-Earth', '/brands/Salt-of-the-Earth/', 'unknown'),
    (249, 'Simply Gentle', 'brandsSimply-Gentle', '/brands/Simply-Gentle/', 'unknown'),
    (255, 'Spry', 'brandsSpry', '/brands/Spry/', 'unknown'),
    (258, 'Suvana', 'brandsSuvana', '/brands/Suvana/', 'unknown'),
    (260, 'Sweet Leaf', 'brandsSweet-Leaf', '/brands/Sweet-Leaf/', 'unknown'),
    (263, 'Symingtons', 'brandsSymingtons', '/brands/Symingtons/', 'unknown'),
    (266, 'Teeccino', 'brandsTeeccino', '/brands/Teeccino/', 'unknown'),
    (268, 'Tints Of Nature', 'brandsTints-of-Nature', '/brands/Tints-of-Nature/', 'unknown'),
    (270, 'Udo''s Choice', 'brandsUdos-Choice', '/brands/Udos-Choice/', 'unknown'),
    (275, 'Vrindavan', 'brandsVrindavan', '/brands/Vrindavan/', 'unknown'),
    (277, 'Wild', 'brandsWild', '/brands/Wild/', 'unknown'),
    (279, 'Wotnot', 'brandsWotnot', '/brands/Wotnot/', 'unknown'),
    (280, 'Yogi Tea', 'brandsYogi-Tea', '/brands/Yogi-Tea/', 'unknown'),
    (287, 'Nature First', 'brandsNature-First', '/brands/Nature-First/', 'unknown'),
    (291, 'Global Organics', 'global-organics', '/global-organics/', 'unknown'),
    (292, 'Puffo''s', 'brandsPuffos', '/brands/Puffos/', 'unknown'),
    (296, 'Herbon', 'brandsHerbon', '/brands/Herbon/', 'unknown'),
    (299, 'Red Seal', 'brandsRed-Seal', '/brands/Red-Seal/', 'unknown'),
    (302, 'Organic Bubs', 'brandsOrganic-Bubs', '/brands/Organic-Bubs/', 'unknown'),
    (304, 'Leda Nutrition', 'leda-nutrition', '/leda-nutrition/', 'unknown'),
    (307, 'Muir Glen', 'brandsMuir-Glen', '/brands/Muir-Glen/', 'unknown'),
    (314, 'Nutritionist Choice', 'brandsNutritionist-Choice', '/brands/Nutritionist-Choice/', 'unknown'),
    (317, 'Hiltona', 'brandsHiltona', '/brands/Hiltona/', 'unknown'),
    (318, 'Clipper', 'brandsClipper', '/brands/Clipper/', 'unknown'),
    (326, 'The Ginger People', 'brandsThe-Ginger-People', '/brands/The-Ginger-People/', 'unknown'),
    (328, 'Kialla Pure Foods', 'brandsKialla-Pure-Foods', '/brands/Kialla-Pure-Foods/', 'unknown'),
    (336, 'EatRite', 'brandsEatrite', '/brands/Eatrite/', 'unknown'),
    (337, 'Sun Valley', 'brandsSun-Valley', '/brands/Sun-Valley/', 'unknown'),
    (340, 'Nirvana', 'brandsNirvana', '/brands/Nirvana/', 'unknown'),
    (343, 'Mayvers', 'brandsMayvers', '/brands/Mayvers/', 'unknown'),
    (355, 'Ambrosia Honey', 'ambrosia-honey', '/ambrosia-honey/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (365, 'Nature''s Cuppa', 'brandsNatures-Cuppa', '/brands/Natures-Cuppa/', 'unknown'),
    (369, 'Celestial', 'brandsCelestial', '/brands/Celestial/', 'unknown'),
    (370, 'Real Good Food', 'brandsReal-Good-Food', '/brands/Real-Good-Food/', 'unknown'),
    (371, 'Body Crystal', 'brandsBody-Crystal', '/brands/Body-Crystal/', 'unknown'),
    (391, 'Martin & Pleasance', 'brandsMartin-and-Pleasance', '/brands/Martin-and-Pleasance/', 'unknown'),
    (393, 'Lakewood', 'brandsLakewood', '/brands/Lakewood/', 'unknown'),
    (400, 'Manuka Health', 'brandsManuka-Health', '/brands/Manuka-Health/', 'unknown'),
    (402, 'Stoney Creek', 'brandsStoney-Creek', '/brands/Stoney-Creek/', 'unknown'),
    (403, 'Alba Hawaiian', 'brandsAlba-Hawaiian', '/brands/Alba-Hawaiian/', 'unknown'),
    (407, 'Avalon Organics', 'avalon-organics', '/avalon-organics/', 'unknown'),
    (421, 'Zen', 'brandsZen', '/brands/Zen/', 'unknown'),
    (425, 'Sutton''s', 'brandsSuttons', '/brands/Suttons/', 'unknown'),
    (437, 'Vital Nutrition', 'brandsVital-Nutrition', '/brands/Vital-Nutrition/', 'unknown'),
    (458, 'Dr Bronner', 'dr-bronners', '/dr-bronners/', 'unknown'),
    (481, 'Jason', 'brandsJason', '/brands/Jason/', 'unknown'),
    (500, 'The Muesli Company', 'brandsThe-Muesli-Company', '/brands/The-Muesli-Company/', 'unknown'),
    (503, 'Neeming Australia', 'brandsNeeming-Australia', '/brands/Neeming-Australia/', 'unknown'),
    (508, 'Acure', 'acure-organics', '/acure-organics/', 'unknown'),
    (509, 'Alaffia', 'brandsALAFFIA', '/brands/ALAFFIA/', 'unknown'),
    (513, 'ALPS', 'brandsALPS', '/brands/ALPS/', 'unknown'),
    (520, 'Bass Brushes', 'brandsBASS-BRUSHES', '/brands/BASS-BRUSHES/', 'unknown'),
    (526, 'Clif Shot Blocks', 'brandsCLIF-SHOT-BLOKS', '/brands/CLIF-SHOT-BLOKS/', 'unknown'),
    (527, 'Clif Shot Energy Gel', 'brandsCLIF-SHOT-ENERGY-GEL', '/brands/CLIF-SHOT-ENERGY-GEL/', 'unknown'),
    (529, 'Colozone Plus', 'brandsCOLOZONE-PLUS', '/brands/COLOZONE-PLUS/', 'unknown'),
    (531, 'Crystal Essence', 'brandsCRYSTAL-ESSENCE', '/brands/CRYSTAL-ESSENCE/', 'unknown'),
    (543, 'Gimme', 'brandsGIMME', '/brands/GIMME/', 'unknown'),
    (544, 'Health 2u', 'brandsHEALTH-2U', '/brands/HEALTH-2U/', 'unknown'),
    (546, 'Honeycone', 'brandsHONEYCONE', '/brands/HONEYCONE/', 'unknown'),
    (549, 'Just Jojoba Aust.', 'brandsJUST-JOJOBA-AUST', '/brands/JUST-JOJOBA-AUST/', 'unknown'),
    (552, 'Natural Rubber Soothers', 'brandsNATURAL-RUBBER-SOOTHERS', '/brands/NATURAL-RUBBER-SOOTHERS/', 'unknown'),
    (554, 'Nature''s Child', 'brandsNATURES-CHILD', '/brands/NATURES-CHILD/', 'unknown'),
    (555, 'Neem Active', 'brandsNEEM-ACTIVE', '/brands/NEEM-ACTIVE/', 'unknown'),
    (559, 'Point Pharma', 'brandsPOINT-PHARMA', '/brands/POINT-PHARMA/', 'unknown'),
    (562, 'Redmond Real Salt', 'brandsREDMOND-REAL-SALT', '/brands/REDMOND-REAL-SALT/', 'unknown'),
    (563, 'Redmond Earthpaste', 'brandsREDMOND-EARTHPASTE', '/brands/REDMOND-EARTHPASTE/', 'unknown'),
    (564, 'Redmond Clay', 'brandsREDMOND-CLAY', '/brands/REDMOND-CLAY/', 'unknown'),
    (565, 'Sakura Health', 'brandsSAKURA-HEALTH', '/brands/SAKURA-HEALTH/', 'unknown'),
    (568, 'Simply Gentle Organic', 'brandsSIMPLY-GENTLE-ORGANIC', '/brands/SIMPLY-GENTLE-ORGANIC/', 'unknown'),
    (570, 'Soleo Organics', 'brandsSOLEO-ORGANICS', '/brands/SOLEO-ORGANICS/', 'unknown'),
    (571, 'Solutions 4 Health', 'brandsSOLUTIONS-4-HEALTH', '/brands/SOLUTIONS-4-HEALTH/', 'unknown'),
    (573, 'T.J. Clark', 'brandsT.J.-CLARK', '/brands/T.J.-CLARK/', 'unknown'),
    (575, 'The Jojoba Company', 'brandsTHE-JOJOBA-COMPANY', '/brands/THE-JOJOBA-COMPANY/', 'unknown'),
    (576, 'Tom Organic', 'brandsTOM-ORGANIC', '/brands/TOM-ORGANIC/', 'unknown'),
    (578, 'Vegesorb', 'brandsVEGESORB', '/brands/VEGESORB/', 'unknown'),
    (579, 'Vital Greens', 'brandsVITAL-GREENS', '/brands/VITAL-GREENS/', 'unknown'),
    (583, 'Vital Protein', 'brandsVITAL-PROTEIN', '/brands/VITAL-PROTEIN/', 'unknown'),
    (591, 'Blue Dinosaur Paleo Bars', 'brandsBLUE-DINOSAUR-PALEO-BARS', '/brands/BLUE-DINOSAUR-PALEO-BARS/', 'unknown'),
    (600, 'Sol Ghee', 'brandsSOL-GHEE', '/brands/SOL-GHEE/', 'unknown'),
    (615, 'Bass Body Care', 'brandsBASS-BODY-CARE', '/brands/BASS-BODY-CARE/', 'unknown'),
    (617, 'Bug-grrr Off', 'brandsbug-grrr-off', '/brands/bug-grrr-off/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (622, 'Nuilife', 'brandsNIULIFE', '/brands/NIULIFE/', 'unknown'),
    (627, 'Zen Green Tea', 'brandsZen-Green-Tea', '/brands/Zen-Green-Tea/', 'unknown'),
    (633, 'Protein Supplies Australia', 'protein-supplies-australia', '/protein-supplies-australia/', 'unknown'),
    (634, 'Bulk', 'brandsBulk', '/brands/Bulk/', 'unknown'),
    (642, 'Lifestream', 'brandsLifestream', '/brands/Lifestream/', 'unknown'),
    (654, '2Die4 Live Foods', 'brands2DIE4-LIVE-FOODS', '/brands/2DIE4-LIVE-FOODS/', 'unknown'),
    (660, 'Extraordinary Foods', 'brandsEXTRAORDINARY-FOODS', '/brands/EXTRAORDINARY-FOODS/', 'unknown'),
    (662, 'Mingle', 'brandsMINGLE', '/brands/MINGLE/', 'unknown'),
    (663, 'My Magic Mud', 'brandsMY-MAGIC-MUD', '/brands/MY-MAGIC-MUD/', 'unknown'),
    (668, 'East Bali Cashews', 'east-bali-cashews', '/east-bali-cashews/', 'unknown'),
    (670, 'Eco Patches', 'brandsECO-PATCHES', '/brands/ECO-PATCHES/', 'unknown'),
    (675, 'Matcha Maiden', 'brandsMATCHA-MAIDEN', '/brands/MATCHA-MAIDEN/', 'unknown'),
    (679, 'Natural Evolution', 'brandsNATURAL-EVOLUTION', '/brands/NATURAL-EVOLUTION/', 'unknown'),
    (680, 'Blooms', 'brandsBlooms', '/brands/Blooms/', 'unknown'),
    (683, 'WOOHOO BODY', 'brandsWOOHOO-BODY', '/brands/WOOHOO-BODY/', 'unknown'),
    (688, 'Cabot Health', 'brandsCabot-Health', '/brands/Cabot-Health/', 'unknown'),
    (697, 'Biologika', 'australian-biologika', '/australian-biologika/', 'unknown'),
    (703, 'Natures Goodness', 'brandsNatures-Goodness', '/brands/Natures-Goodness/', 'unknown'),
    (719, 'Hanami', 'brandsHANAMI', '/brands/HANAMI/', 'unknown'),
    (721, 'Jojoba Company', 'brandsJojoba-Company', '/brands/Jojoba-Company/', 'unknown'),
    (723, 'Little Mashies', 'brandsLITTLE-MASHIES', '/brands/LITTLE-MASHIES/', 'unknown'),
    (728, 'Ever Eco', 'brandsever-eco', '/brands/ever-eco/', 'unknown'),
    (730, 'Supercharged Food', 'brandsSupercharged-Food', '/brands/Supercharged-Food/', 'unknown'),
    (734, 'The Whole Foodies', 'brandsThe-Whole-Foodies', '/brands/The-Whole-Foodies/', 'unknown'),
    (742, 'Little Zebra', 'brandsLITTLE-ZEBRA', '/brands/LITTLE-ZEBRA/', 'unknown'),
    (748, 'Teelixir', 'brandsTeelixir', '/brands/Teelixir/', 'unknown'),
    (754, 'Luvin Life', 'brandsLuvin-Life', '/brands/Luvin-Life/', 'unknown'),
    (755, 'Klean Kanteen', 'brandsKlean-Kanteen', '/brands/Klean-Kanteen/', 'unknown'),
    (758, 'Dead Sea Warehouse', 'brandsDEAD-SEA-WAREHOUSE', '/brands/DEAD-SEA-WAREHOUSE/', 'unknown'),
    (759, 'That Red House', 'brandsThat-Red-House', '/brands/That-Red-House/', 'unknown'),
    (763, 'Vego', 'brandsVEGO', '/brands/VEGO/', 'unknown'),
    (764, 'Nulax', 'brandsNulax', '/brands/Nulax/', 'unknown'),
    (767, 'Berringa', 'brandsBerringa', '/brands/Berringa/', 'unknown'),
    (770, 'Bennetto', 'brandsBennetto', '/brands/Bennetto/', 'unknown'),
    (772, 'Naturtint', 'brandsNaturTint', '/brands/NaturTint/', 'unknown'),
    (780, 'Botanika Blends', 'botanika-blends', '/botanika-blends/', 'unknown'),
    (782, 'GF Oats', 'gf-oats', '/gf-oats/', 'unknown'),
    (785, 'Byron Bay Cookies', 'byron-bay-cookies', '/byron-bay-cookies/', 'unknown'),
    (786, 'The Gluten Free Food Co', 'the-gluten-free-food-co', '/the-gluten-free-food-co/', 'unknown'),
    (787, 'Apiwraps', 'apiwraps', '/apiwraps/', 'unknown'),
    (788, 'Bon Ami', 'bon-ami', '/bon-ami/', 'unknown'),
    (790, 'Byron Naturals', 'byron-naturals', '/byron-naturals/', 'unknown'),
    (791, 'Ecococonut', 'ecococonut', '/ecococonut/', 'unknown'),
    (792, 'Eclipse Organics', 'eclipse-organics', '/eclipse-organics/', 'unknown'),
    (800, 'Lunette', 'lunette', '/lunette/', 'unknown'),
    (801, 'Little Zebra Chocolates', 'little-zebra-chocolates', '/little-zebra-chocolates/', 'unknown'),
    (803, 'Monday Food Co', 'monday-food-co', '/monday-food-co/', 'unknown'),
    (808, 'The Protein Bread Co', 'protein-bread-co', '/protein-bread-co/', 'unknown'),
    (811, 'Evodia', 'evodia', '/evodia/', 'unknown'),
    (812, 'Schmidts', 'schmidts-deodorant', '/schmidts-deodorant/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (814, 'Tooshies By Tom', 'tooshies-by-tom', '/tooshies-by-tom/', 'unknown'),
    (817, 'Uptons Naturals', 'uptons-naturals', '/uptons-naturals/', 'unknown'),
    (826, 'Abode Cleaning Products', 'brandsabode-cleaning-products', '/brands/abode-cleaning-products/', 'unknown'),
    (827, 'Absolute Fruitz', 'brandsAbsolute-Fruitz', '/brands/Absolute-Fruitz/', 'unknown'),
    (828, 'Absolute Green', 'brandsAbsolute-Green', '/brands/Absolute-Green/', 'unknown'),
    (831, 'Advanced Health Products', 'brandsAdvanced-Health-Products', '/brands/Advanced-Health-Products/', 'unknown'),
    (832, 'Advanced Medicine', 'brandsAdvanced-Medicine', '/brands/Advanced-Medicine/', 'unknown'),
    (834, 'Alter Dist', 'brandsAlter-Dist', '/brands/Alter-Dist/', 'unknown'),
    (839, 'Araman', 'brandsAraman', '/brands/Araman/', 'unknown'),
    (840, 'Arkopharma', 'brandsArkopharma', '/brands/Arkopharma/', 'unknown'),
    (841, 'Aromamatic Products', 'brandsAromamatic-Products', '/brands/Aromamatic-Products/', 'unknown'),
    (844, 'Ayuna', 'brandsAyuna', '/brands/Ayuna/', 'unknown'),
    (846, 'Bee Natural', 'brandsBee-Natural', '/brands/Bee-Natural/', 'unknown'),
    (847, 'Berringa Honey', 'brandsBerringa-Honey', '/brands/Berringa-Honey/', 'unknown'),
    (848, 'Bioeffective By Taiga', 'brandsBioeffective-By-Taiga', '/brands/Bioeffective-By-Taiga/', 'unknown'),
    (850, 'Biorevive', 'brandsBiorevive', '/brands/Biorevive/', 'unknown'),
    (852, 'Bonvit', 'brandsBonvit', '/brands/Bonvit/', 'unknown'),
    (857, 'Boomers Whey Protein', 'brandsBoomers-Whey-Protein', '/brands/Boomers-Whey-Protein/', 'unknown'),
    (858, 'Botani', 'brandsBotan', '/brands/Botan/', 'unknown'),
    (860, 'Brauer', 'brandsBrauer', '/brands/Brauer/', 'unknown'),
    (861, 'BSKT', 'brandsBskt', '/brands/Bskt/', 'unknown'),
    (862, 'Byron Bath Salts', 'brandsByron-Bath-Salts', '/brands/Byron-Bath-Salts/', 'unknown'),
    (864, 'Byron Bay Medicinal Herbs', 'brandsByron-Bay-Medicinal-Herbs', '/brands/Byron-Bay-Medicinal-Herbs/', 'unknown'),
    (865, 'Caprilac', 'brandsCaprilac', '/brands/Caprilac/', 'unknown'),
    (867, 'Carwari', 'brandsCarwari', '/brands/Carwari/', 'unknown'),
    (868, 'Cathay Herbal Retail', 'brandsCathay-Herbal-Retail', '/brands/Cathay-Herbal-Retail/', 'unknown'),
    (869, 'Cell-logic Practitioner', 'brandsCell-logic-Practitioner', '/brands/Cell-logic-Practitioner/', 'unknown'),
    (870, 'Cell-logic Retail', 'brandsCell-logic-Retail', '/brands/Cell-logic-Retail/', 'unknown'),
    (872, 'Clover Fields', 'brandsClover-Fields', '/brands/Clover-Fields/', 'unknown'),
    (875, 'Concord Eye Care', 'brandsConcord-Eye-Care', '/brands/Concord-Eye-Care/', 'unknown'),
    (876, 'Concord Retail', 'brandsConcord-Retail', '/brands/Concord-Retail/', 'unknown'),
    (878, 'Couleur Caramel', 'brandsCouleur-Caramel', '/brands/Couleur-Caramel/', 'unknown'),
    (880, 'Deonat', 'brandsDeonat', '/brands/Deonat/', 'unknown'),
    (881, 'Derma E', 'brandsDerma-E', '/brands/Derma-E/', 'unknown'),
    (882, 'Dermal Therapy', 'brandsDermal-Therapy', '/brands/Dermal-Therapy/', 'unknown'),
    (884, 'Dr Wheatgrass', 'brandsDr-Wheatgrass', '/brands/Dr-Wheatgrass/', 'unknown'),
    (885, 'Easy Ph', 'brandsEasy-Ph', '/brands/Easy-Ph/', 'unknown'),
    (886, 'Eco Coconut', 'brandsEco-Coconut', '/brands/Eco-Coconut/', 'unknown'),
    (888, 'Eco Modern Essentials', 'brandsEco-Modern-Essentials', '/brands/Eco-Modern-Essentials/', 'unknown'),
    (889, 'EnviroCare', 'brandsEnvirocare', '/brands/Envirocare/', 'unknown'),
    (890, 'EnviroClean', 'brandsEnviroclean', '/brands/Enviroclean/', 'unknown'),
    (891, 'Enviropet', 'brandsEnviropet', '/brands/Enviropet/', 'unknown'),
    (892, 'Epic Dental', 'brandsEpic-Dental', '/brands/Epic-Dental/', 'unknown'),
    (893, 'Equinox Botanicals', 'brandsEquinox-Botanicals', '/brands/Equinox-Botanicals/', 'unknown'),
    (895, 'Essential Therapeutics', 'brandsEssential-Therapeutics', '/brands/Essential-Therapeutics/', 'unknown'),
    (896, 'Essenzza', 'brandsEssenzza', '/brands/Essenzza/', 'unknown'),
    (897, 'Fermentanicals', 'brandsFermentanicals', '/brands/Fermentanicals/', 'unknown'),
    (898, 'Fes Flower Essences', 'brandsFes-Flower-Essences', '/brands/Fes-Flower-Essences/', 'unknown'),
    (900, 'Fijian Noni', 'brandsFijian-Noni', '/brands/Fijian-Noni/', 'unknown'),
    (902, 'Flora Remedia', 'brandsFlora-Remedia', '/brands/Flora-Remedia/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (904, 'Floradix', 'brandsFloradix', '/brands/Floradix/', 'unknown'),
    (905, 'Flordis', 'brandsFlordis', '/brands/Flordis/', 'unknown'),
    (906, 'Footsies By Thnklife', 'brandsFootsies-By-Thnklife', '/brands/Footsies-By-Thnklife/', 'unknown'),
    (907, 'Fresca Natural', 'brandsFresca-Natural', '/brands/Fresca-Natural/', 'unknown'),
    (908, 'Fulhealth Industries', 'brandsFulhealth-Industries', '/brands/Fulhealth-Industries/', 'unknown'),
    (910, 'Glimlife', 'brandsGlimlife', '/brands/Glimlife/', 'unknown'),
    (911, 'Goat Range', 'brandsGoat-Range', '/brands/Goat-Range/', 'unknown'),
    (912, 'Grahams Natural Alternatives', 'brandsGrahams-Natural-Alternatives', '/brands/Grahams-Natural-Alternatives/', 'unknown'),
    (914, 'Healing Concepts Teas', 'brandsHealing-Concepts-Teas', '/brands/Healing-Concepts-Teas/', 'unknown'),
    (916, 'Healr', 'brandsHealr', '/brands/Healr/', 'unknown'),
    (917, 'Health Kultcha', 'brandsHealth-Kultcha', '/brands/Health-Kultcha/', 'unknown'),
    (918, 'Healthwise', 'brandsHealthwise', '/brands/Healthwise/', 'unknown'),
    (919, 'Heel', 'brandsHeel', '/brands/Heel/', 'unknown'),
    (920, 'Helio Supply Co', 'brandsHelio-Supply-Co', '/brands/Helio-Supply-Co/', 'unknown'),
    (921, 'Herbal Extract Company Misc', 'brandsHerbal-Extract-Company-Misc', '/brands/Herbal-Extract-Company-Misc/', 'unknown'),
    (922, 'Herbal Wellbeing', 'brandsHerbal-Wellbeing', '/brands/Herbal-Wellbeing/', 'unknown'),
    (923, 'Honey Life', 'brandsHoney-Life', '/brands/Honey-Life/', 'unknown'),
    (926, 'Interclinical Laboratories', 'brandsInterclinical-Laboratories', '/brands/Interclinical-Laboratories/', 'unknown'),
    (929, 'Jak Organics', 'brandsJak-Organics', '/brands/Jak-Organics/', 'unknown'),
    (931, 'Joonya', 'brandsJoonya', '/brands/Joonya/', 'unknown'),
    (934, 'Kuranda', 'brandsKuranda', '/brands/Kuranda/', 'unknown'),
    (936, 'Lacteeze By Allergy Free', 'brandsLacteeze-By-Allergy-Free', '/brands/Lacteeze-By-Allergy-Free/', 'unknown'),
    (937, 'Lifesprings', 'brandsLifesprings', '/brands/Lifesprings/', 'unknown'),
    (938, 'Lifestart Naturopathics', 'brandsLifestart-Naturopathics', '/brands/Lifestart-Naturopathics/', 'unknown'),
    (941, 'Little Urchin', 'brandsLittle-Urchin', '/brands/Little-Urchin/', 'unknown'),
    (942, 'Living Essences', 'brandsLiving-Essences', '/brands/Living-Essences/', 'unknown'),
    (943, 'Livinia Natural', 'brandsLivinia-Natural', '/brands/Livinia-Natural/', 'unknown'),
    (946, 'Love Tea', 'brandsLove-Tea', '/brands/Love-Tea/', 'unknown'),
    (947, 'Lucas Pawpaw Remedies', 'brandsLucas-Pawpaw-Remedies', '/brands/Lucas-Pawpaw-Remedies/', 'unknown'),
    (949, 'Mageze', 'brandsMageze', '/brands/Mageze/', 'unknown'),
    (951, 'Maharishi', 'brandsMaharishi', '/brands/Maharishi/', 'unknown'),
    (955, 'Megaburn', 'brandsMegaburn', '/brands/Megaburn/', 'unknown'),
    (956, 'Melrose', 'brandsMelrose', '/brands/Melrose/', 'unknown'),
    (957, 'Microrganics', 'brandsMicrorganics', '/brands/Microrganics/', 'unknown'),
    (958, 'Millenium Pharmaceuticals', 'brandsMillenium-Pharmaceuticals', '/brands/Millenium-Pharmaceuticals/', 'unknown'),
    (961, 'Mount Romance', 'brandsMount-Romance', '/brands/Mount-Romance/', 'unknown'),
    (964, 'My New Skin By Arkomega', 'brandsMy-New-Skin-By-Arkomega', '/brands/My-New-Skin-By-Arkomega/', 'unknown'),
    (965, 'Mygen Health', 'brandsMygen-Health', '/brands/Mygen-Health/', 'unknown'),
    (968, 'Natra Choice', 'brandsNatra-Choice', '/brands/Natra-Choice/', 'unknown'),
    (970, 'Natralus', 'brandsNatralus', '/brands/Natralus/', 'unknown'),
    (971, 'Natural Health', 'brandsNatural-Health', '/brands/Natural-Health/', 'unknown'),
    (972, 'Natural Instinct', 'brandsNatural-Instinct', '/brands/Natural-Instinct/', 'unknown'),
    (973, 'Natural Remedy Tonics', 'brandsNatural-Remedy-Tonics', '/brands/Natural-Remedy-Tonics/', 'unknown'),
    (979, 'Natures Delight', 'brandsNatures-Delight', '/brands/Natures-Delight/', 'unknown'),
    (981, 'Necessity', 'brandsNecessity', '/brands/Necessity/', 'unknown'),
    (985, 'Nutralife', 'brandsNutralife', '/brands/Nutralife/', 'unknown'),
    (989, 'Only Emu', 'brandsOnly-Emu', '/brands/Only-Emu/', 'unknown'),
    (990, 'Onya', 'brandsOnya', '/brands/Onya/', 'unknown'),
    (991, 'Onya For Life', 'brandsOnya-For-Life', '/brands/Onya-For-Life/', 'unknown'),
    (993, 'Organic Botanicals', 'brandsOrganic-Botanicals', '/brands/Organic-Botanicals/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (996, 'Oureco', 'brandsOureco', '/brands/Oureco/', 'unknown'),
    (998, 'Oxymin', 'brandsOxymin', '/brands/Oxymin/', 'unknown'),
    (999, 'Ozhealth', 'brandsOzhealth', '/brands/Ozhealth/', 'unknown'),
    (1002, 'Paw By Blackmores', 'brandsPaw-By-Blackmores', '/brands/Paw-By-Blackmores/', 'unknown'),
    (1004, 'Perfect Health Solutions', 'brandsPerfect-Health-Solutions', '/brands/Perfect-Health-Solutions/', 'unknown'),
    (1008, 'Primal Nature', 'brandsPrimal-Nature', '/brands/Primal-Nature/', 'unknown'),
    (1013, 'Pure Eden', 'brandsPure-Eden', '/brands/Pure-Eden/', 'unknown'),
    (1017, 'Rainforest Remedies', 'brandsRainforest-Remedies', '/brands/Rainforest-Remedies/', 'unknown'),
    (1020, 'Raw Food Factory', 'brandsRaw-Food-Factory', '/brands/Raw-Food-Factory/', 'unknown'),
    (1021, 'Refresh Byron Bay', 'brandsRefresh-Byron-Bay', '/brands/Refresh-Byron-Bay/', 'unknown'),
    (1022, 'Rhinomed Mute', 'brandsRhinomed-Mute', '/brands/Rhinomed-Mute/', 'unknown'),
    (1023, 'Rochester', 'brandsRochester', '/brands/Rochester/', 'unknown'),
    (1024, 'Rochway', 'brandsRochway', '/brands/Rochway/', 'unknown'),
    (1025, 'Ross Gardiner', 'brandsRoss-Gardiner', '/brands/Ross-Gardiner/', 'unknown'),
    (1028, 'Sativa', 'brandsSativa', '/brands/Sativa/', 'unknown'),
    (1029, 'Seipel Health', 'brandsSeipel-Health', '/brands/Seipel-Health/', 'unknown'),
    (1030, 'Seven Wonders', 'brandsSeven-Wonders', '/brands/Seven-Wonders/', 'unknown'),
    (1031, 'Skin Tonic By Tea Tonic', 'brandsSkin-Tonic-By-Tea-Tonic', '/brands/Skin-Tonic-By-Tea-Tonic/', 'unknown'),
    (1033, 'Spectrum Herbal', 'brandsSpectrum-Herbal', '/brands/Spectrum-Herbal/', 'unknown'),
    (1034, 'Strath', 'brandsStrath', '/brands/Strath/', 'unknown'),
    (1036, 'Sweet Life', 'brandsSweet-Life', '/brands/Sweet-Life/', 'unknown'),
    (1038, 'Sylk', 'brandsSylk', '/brands/Sylk/', 'unknown'),
    (1039, 'Synergy Natural', 'brandsSynergy-Natural', '/brands/Synergy-Natural/', 'unknown'),
    (1041, 'Tea Tonic', 'brandsTea-Tonic', '/brands/Tea-Tonic/', 'unknown'),
    (1046, 'The Lupin Co', 'brandsThe-Lupin-Co', '/brands/The-Lupin-Co/', 'unknown'),
    (1047, 'The Natural Family Co', 'brandsThe-Natural-Family-Co', '/brands/The-Natural-Family-Co/', 'unknown'),
    (1049, 'Therapacks', 'brandsTherapacks', '/brands/Therapacks/', 'unknown'),
    (1051, 'Tisserand', 'brandsTisserand', '/brands/Tisserand/', 'unknown'),
    (1054, 'Vabori', 'brandsVabori', '/brands/Vabori/', 'unknown'),
    (1058, 'Vogel', 'brandsVogel', '/brands/Vogel/', 'unknown'),
    (1059, 'Weleda', 'brandsWeleda', '/brands/Weleda/', 'unknown'),
    (1062, 'Wise Nutrients', 'brandsWise-Nutrients', '/brands/Wise-Nutrients/', 'unknown'),
    (1063, 'Xlear', 'brandsXlear', '/brands/Xlear/', 'unknown'),
    (1066, 'Zeb Health', 'brandsZeb-Health', '/brands/Zeb-Health/', 'unknown'),
    (1067, 'Zen Therapeutics', 'brandsZen-Therapeutics', '/brands/Zen-Therapeutics/', 'unknown'),
    (1107, 'Clean & Green Wholefoods', 'clean-green-wholefoods', '/clean-green-wholefoods/', 'unknown'),
    (1108, 'Corporate Health & Safety', 'corporate-health-safety', '/corporate-health-safety/', 'unknown'),
    (1112, 'MARTIN & PLEASANCE VITAL', 'martin-pleasance-vital', '/martin-pleasance-vital/', 'unknown'),
    (1113, 'Nature''s Pet', 'natures-pet', '/natures-pet/', 'unknown'),
    (1114, 'Nature''s Sunshine', 'natures-sunshine-1', '/natures-sunshine-1/', 'unknown'),
    (1115, 'Ouch!', 'ouch', '/ouch/', 'unknown'),
    (1116, 'Amenas Sea Minerals', 'amenas-sea-minerals', '/amenas-sea-minerals/', 'unknown'),
    (1117, 'Nature''s Shield', 'natures-shield', '/natures-shield/', 'unknown'),
    (1119, 'Percy''s Products', 'percys-products', '/percys-products/', 'unknown'),
    (1120, 'Bobs Red Mill', 'bobs-red-mill', '/bobs-red-mill/', 'unknown'),
    (1122, 'Biotta', 'brandsBIOTTA', '/brands/BIOTTA/', 'unknown'),
    (1125, 'Elmore Oil', 'brandsELMORE-OIL', '/brands/ELMORE-OIL/', 'unknown'),
    (1128, 'Herbs of Gold', 'brandsHERBS-OF-GOLD', '/brands/HERBS-OF-GOLD/', 'unknown'),
    (1129, 'Hilde Hemmes', 'brandsHILDE-HEMMES', '/brands/HILDE-HEMMES/', 'unknown'),
    (1133, 'Kiwiherb', 'brandsKIWIHERB', '/brands/KIWIHERB/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (1134, 'Meditree', 'brandsMEDITREE', '/brands/MEDITREE/', 'unknown'),
    (1135, 'Mt Somers', 'brandsMT-SOMERS', '/brands/MT-SOMERS/', 'unknown'),
    (1139, 'Reach for Life', 'brandsREACH-FOR-LIFE', '/brands/REACH-FOR-LIFE/', 'unknown'),
    (1140, 'Rosa Naturals', 'brandsROSA-NATURALS', '/brands/ROSA-NATURALS/', 'unknown'),
    (1144, 'Wonder Foods', 'brandsWONDER-FOODS', '/brands/WONDER-FOODS/', 'unknown'),
    (1155, 'Kallo', 'brandsKallo', '/brands/Kallo/', 'unknown'),
    (1169, 'Chico Bag', 'brandsCHICO-BAG', '/brands/CHICO-BAG/', 'unknown'),
    (1171, 'Chandrika', 'brandsChandrika', '/brands/Chandrika/', 'unknown'),
    (1178, 'Apple Green Duck', 'brandsAPPLE-GREEN-DUCK', '/brands/APPLE-GREEN-DUCK/', 'unknown'),
    (1190, 'Happy Way', 'brandsHAPPY-WAY', '/brands/HAPPY-WAY/', 'unknown'),
    (1192, 'Noble Jerky', 'brandsNOBLE-JERKY', '/brands/NOBLE-JERKY/', 'unknown'),
    (1237, 'King Soba', 'brandsKING-SOBA', '/brands/KING-SOBA/', 'unknown'),
    (1239, '24k Goddess', 'brands24K-GODDESS', '/brands/24K-GODDESS/', 'unknown'),
    (1319, 'SkinB5', 'brandsSKINB5', '/brands/SKINB5/', 'unknown'),
    (1339, 'Natural Value', 'brandsNATURAL-VALUE', '/brands/NATURAL-VALUE/', 'unknown'),
    (5217, 'Kadac', 'kadac', '/kadac/', 'unknown'),
    (5220, 'Earthwise', 'earthwise', '/earthwise/', 'unknown'),
    (5221, 'Recipes', 'recipes', '/recipes/', 'unknown'),
    (5229, 'Hannahpad', 'hannahpad', '/hannahpad/', 'unknown'),
    (5230, 'Organicup', 'organicup', '/organicup/', 'unknown'),
    (5231, 'Koala Eco', 'koala-eco', '/koala-eco/', 'unknown'),
    (5233, 'Shampoo With A Purpose', 'shampoo-with-a-purpose', '/shampoo-with-a-purpose/', 'unknown'),
    (5235, 'Biotuff', 'biotuff', '/biotuff/', 'unknown'),
    (5239, 'Ethical Zinc', 'ethical-zinc', '/ethical-zinc/', 'unknown'),
    (5241, 'Medicines From Nature', 'medicines-from-nature', '/medicines-from-nature/', 'unknown'),
    (5245, 'Marco Polo''s Treasure', 'marco-polos-treasure', '/marco-polos-treasure/', 'unknown'),
    (5252, 'Vivo', 'vivo', '/vivo/', 'unknown'),
    (5256, 'Desert Island Confectionery', 'desert-island-confectionery', '/desert-island-confectionery/', 'unknown'),
    (5259, 'Wrappa', 'wrappa', '/wrappa/', 'unknown'),
    (5260, 'Essential Hemp', 'essential-hemp', '/essential-hemp/', 'unknown'),
    (5262, 'Retrokitchen', 'retrokitchen', '/retrokitchen/', 'unknown'),
    (5267, 'Zuii Organic', 'zuii-organic', '/zuii-organic/', 'unknown'),
    (5270, 'Wheatbags Love', 'wheatbags-love', '/wheatbags-love/', 'unknown'),
    (5271, 'Pbco', 'pbco', '/pbco/', 'unknown'),
    (5272, 'Planet Luxe', 'planet-luxe', '/planet-luxe/', 'unknown'),
    (5319, 'Broth & Co', 'brandsBroth-Co', '/brands/Broth-Co/', 'unknown'),
    (5323, 'Happy Hippie', 'brandsHappyHippie', '/brands/HappyHippie/', 'unknown'),
    (5329, 'Antipodes', 'brandsANTIPODES', '/brands/ANTIPODES/', 'unknown'),
    (5330, 'Atmosphere', 'brandsATMOSPHERE', '/brands/ATMOSPHERE/', 'unknown'),
    (5331, 'Australian Creams', 'brandsAUSTRALIANCREAMS', '/brands/AUSTRALIANCREAMS/', 'unknown'),
    (5332, 'Australian Creams Mk II', 'brandsAUSTRALIANCREAMSMKII', '/brands/AUSTRALIANCREAMSMKII/', 'unknown'),
    (5333, 'Australian Healing Clay', 'brandsAUSTRALIANHEALINGCLAY', '/brands/AUSTRALIANHEALINGCLAY/', 'unknown'),
    (5335, 'Biosun Earcandle', 'brandsBIOSUNEARCANDLE', '/brands/BIOSUNEARCANDLE/', 'unknown'),
    (5336, 'Boomers Protein', 'brandsBOOMERSPROTEIN', '/brands/BOOMERSPROTEIN/', 'unknown'),
    (5337, 'Bundys Health', 'brandsBUNDYSHEALTH', '/brands/BUNDYSHEALTH/', 'unknown'),
    (5339, 'Cell Logic', 'brandsCELLLOGIC', '/brands/CELLLOGIC/', 'unknown'),
    (5340, 'Distillery Fragrance House', 'brandsDISTILLERYFRAGRANCEHOUSE', '/brands/DISTILLERYFRAGRANCEHOUSE/', 'unknown'),
    (5354, 'Entity Health', 'brandsENTITYHEALTH', '/brands/ENTITYHEALTH/', 'unknown'),
    (5355, 'Enviromedica', 'brandsENVIROMEDICA', '/brands/ENVIROMEDICA/', 'unknown'),
    (5356, 'Fiji Kava', 'brandsFIJIKAVA', '/brands/FIJIKAVA/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (5357, 'Flexeze', 'brandsFLEXEZE', '/brands/FLEXEZE/', 'unknown'),
    (5359, 'Goodmix', 'brandsGOODMIX', '/brands/GOODMIX/', 'unknown'),
    (5360, 'Grounded', 'brandsGROUNDED', '/brands/GROUNDED/', 'unknown'),
    (5361, 'Henry Blooms', 'brandsHENRYBLOOMS', '/brands/HENRYBLOOMS/', 'unknown'),
    (5384, 'Jo Olley', 'brandsJOOLLEY', '/brands/JOOLLEY/', 'unknown'),
    (5386, 'Locako', 'brandsLOCAKO', '/brands/LOCAKO/', 'unknown'),
    (5388, 'Mad Millie', 'brandsMADMILLIE', '/brands/MADMILLIE/', 'unknown'),
    (5389, 'Minimal Essentials', 'brandsMINIMALESSENTIALS', '/brands/MINIMALESSENTIALS/', 'unknown'),
    (5390, 'Modifilan', 'brandsMODIFILAN', '/brands/MODIFILAN/', 'unknown'),
    (5391, 'Mthfr Group', 'brandsMTHFRGROUP', '/brands/MTHFRGROUP/', 'unknown'),
    (5393, 'Natrachoice', 'brandsNATRACHOICE', '/brands/NATRACHOICE/', 'unknown'),
    (5394, 'Naturobest', 'brandsNATUROBEST', '/brands/NATUROBEST/', 'unknown'),
    (5395, 'Nc By Nutrition Care', 'brandsNCbyNUTRITIONCARE', '/brands/NCbyNUTRITIONCARE/', 'unknown'),
    (5396, 'Norfolk Punch', 'brandsNORFOLKPUNCH', '/brands/NORFOLKPUNCH/', 'unknown'),
    (5485, 'Nutra Organics', 'brandsNUTRAORGANICSWHOLEFOODPANTRY', '/brands/NUTRAORGANICSWHOLEFOODPANTRY/', 'unknown'),
    (5487, 'Oil Garden', 'brandsOILGARDEN', '/brands/OILGARDEN/', 'unknown'),
    (5488, 'Omega', 'brandsOMEGA', '/brands/OMEGA/', 'unknown'),
    (5489, 'Orielton Laboratories', 'brandsORIELTONLABORATORIES', '/brands/ORIELTONLABORATORIES/', 'unknown'),
    (5491, 'Papaya Activs', 'brandsPAPAYAACTIVS', '/brands/PAPAYAACTIVS/', 'unknown'),
    (5492, 'Pawsome Organics', 'brandsPAWSOMEORGANICS', '/brands/PAWSOMEORGANICS/', 'unknown'),
    (5494, 'Phytality Nutrition', 'brandsPHYTALITYNUTRITION', '/brands/PHYTALITYNUTRITION/', 'unknown'),
    (5495, 'Premedy', 'brandsPREMEDY', '/brands/PREMEDY/', 'unknown'),
    (5496, 'Pretorius', 'brandsPRETORIUS', '/brands/PRETORIUS/', 'unknown'),
    (5497, 'Pure Papayacare', 'brandsPUREPAPAYACARE', '/brands/PUREPAPAYACARE/', 'unknown'),
    (5498, 'Raw Medicine', 'brandsRAWMEDICINE', '/brands/RAWMEDICINE/', 'unknown'),
    (5499, 'Realchai', 'brandsREALCHAI', '/brands/REALCHAI/', 'unknown'),
    (5500, 'Regrow Hair Clinics', 'brandsREGROWHAIRCLINICS', '/brands/REGROWHAIRCLINICS/', 'unknown'),
    (5501, 'Saltco', 'brandsSALTCO', '/brands/SALTCO/', 'unknown'),
    (5502, 'Sanum', 'brandsSANUM', '/brands/SANUM/', 'unknown'),
    (5503, 'Shady Maple Farms', 'brandsSHADYMAPLEFARMS', '/brands/SHADYMAPLEFARMS/', 'unknown'),
    (5504, 'Silicea', 'brandsSILICEA', '/brands/SILICEA/', 'unknown'),
    (5505, 'Spectrum Herbal Tao', 'brandsSPECTRUMHERBALTAO', '/brands/SPECTRUMHERBALTAO/', 'unknown'),
    (5510, 'Titree Spirit Herbals', 'brandsTITREESPIRITHERBALS', '/brands/TITREESPIRITHERBALS/', 'unknown'),
    (5511, 'Tonika', 'brandsTONIKA', '/brands/TONIKA/', 'unknown'),
    (5513, 'Vicco', 'brandsVICCO', '/brands/VICCO/', 'unknown'),
    (5514, 'Waterpark Farm', 'brandsWATERPARKFARM', '/brands/WATERPARKFARM/', 'unknown'),
    (5515, 'Well Naturally', 'brandsWELLNATURALLY', '/brands/WELLNATURALLY/', 'unknown'),
    (5519, 'Woohoo', 'brandsWOOHOO', '/brands/WOOHOO/', 'unknown'),
    (5520, 'Plantasy Foods', 'plantasy-foods', '/plantasy-foods/', 'unknown'),
    (5524, 'Beggi', 'beggi', '/beggi/', 'unknown'),
    (5529, 'Ethique', 'ethique', '/ethique/', 'unknown'),
    (5855, 'Vander Kraats', 'brandsVANDERKRAATS', '/brands/VANDERKRAATS/', 'unknown'),
    (6002, 'The Hello Cup', 'the-hello-cup', '/the-hello-cup/', 'unknown'),
    (6006, 'Koja', 'koja', '/koja/', 'unknown'),
    (6009, 'Macro Mike', 'macro-mike', '/macro-mike/', 'unknown'),
    (6010, 'The Monday Food Co', 'the-monday-food-co', '/the-monday-food-co/', 'unknown'),
    (6011, 'Natures Gifts', 'natures-gifts', '/natures-gifts/', 'unknown'),
    (6614, 'Amala', 'amala', '/amala/', 'unknown'),
    (6660, 'Morlife', 'morlife', '/morlife/', 'unknown'),
    (6662, 'Twist', 'twist', '/twist/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (6685, 'Medical Medium', 'medical-medium', '/medical-medium/', 'unknown'),
    (6687, 'Evolution Botanicals', 'evolution-botanicals', '/evolution-botanicals/', 'unknown'),
    (7256, 'Rejuvin8tion', 'brandsREJUVIN-TION', '/brands/REJUVIN-TION/', 'unknown'),
    (8081, 'Barbell Foods', 'brandsBarbellFoods', '/brands/BarbellFoods/', 'unknown'),
    (8082, 'Bains Wholefoods', 'brandsBainsWholefoods', '/brands/BainsWholefoods/', 'unknown'),
    (8083, 'The Carob Kitchen', 'brandsTheCarobKitchen', '/brands/TheCarobKitchen/', 'unknown'),
    (8084, 'Denmar International', 'brandsDenmarInternational', '/brands/DenmarInternational/', 'unknown'),
    (8087, 'Complete Health', 'brandsCompleteHealth', '/brands/CompleteHealth/', 'unknown'),
    (8088, 'Cobs', 'brandsCobs', '/brands/Cobs/', 'unknown'),
    (8089, 'EBO RAW', 'brandsEBORAW', '/brands/EBORAW/', 'unknown'),
    (8091, 'Emu Tracks', 'brandsEmuTracks', '/brands/EmuTracks/', 'unknown'),
    (8093, 'Flor Essence', 'brandsFlorEssence', '/brands/FlorEssence/', 'unknown'),
    (8096, 'Kookas Natural', 'brandsKookasNatural', '/brands/KookasNatural/', 'unknown'),
    (8097, 'Food To Nourish', 'brandsFoodtoNourish', '/brands/FoodtoNourish/', 'unknown'),
    (8098, 'Good Morning Cereals', 'brandsGoodMorningCereals', '/brands/GoodMorningCereals/', 'unknown'),
    (8099, 'Gelatin Health', 'brandsGelatinHealth', '/brands/GelatinHealth/', 'unknown'),
    (8100, 'Goli Nutrition', 'brandsgoli-nutrition', '/brands/goli-nutrition/', 'unknown'),
    (8101, 'Greenback Plant Protein', 'brandsGreenbackPlantProtein', '/brands/GreenbackPlantProtein/', 'unknown'),
    (8106, 'Jimalie Coconut Products', 'brandsJimalieCoconutProducts', '/brands/JimalieCoconutProducts/', 'unknown'),
    (8108, 'Coco Earth', 'brandsCocoEarth', '/brands/CocoEarth/', 'unknown'),
    (8109, 'Loving Earth', 'brandsLovingEarth', '/brands/LovingEarth/', 'unknown'),
    (8110, 'Life Cycle', 'brandsLifeCykel', '/brands/LifeCykel/', 'unknown'),
    (8111, 'Lenny & Larry', 'brandsLenny-Larry', '/brands/Lenny-Larry/', 'unknown'),
    (8113, 'Marigold Health Foods', 'brandsMarigoldHealthFoods', '/brands/MarigoldHealthFoods/', 'unknown'),
    (8117, 'Nutraviva', 'brandsNutraviva', '/brands/Nutraviva/', 'unknown'),
    (8118, 'Nirvana Originals', 'brandsNirvanaOriginals', '/brands/NirvanaOriginals/', 'unknown'),
    (8120, 'Orgran Gluten Free', 'brandsOrgranGlutenFree', '/brands/OrgranGlutenFree/', 'unknown'),
    (8121, 'Organic India', 'brandsOrganicIndia', '/brands/OrganicIndia/', 'unknown'),
    (8123, 'Simply Clean', 'brandsSimplyClean', '/brands/SimplyClean/', 'unknown'),
    (8124, 'Spiral Foods', 'brandsSpiralFoods', '/brands/SpiralFoods/', 'unknown'),
    (8134, 'Simply 7', 'brandsSimply', '/brands/Simply/', 'unknown'),
    (8135, 'Slendier', 'brandsSlendier', '/brands/Slendier/', 'unknown'),
    (8141, 'Thankfully Nourished', 'brandsThankfullyNourished', '/brands/ThankfullyNourished/', 'unknown'),
    (8142, 'Tonik Pro', 'brandsTonikPro', '/brands/TonikPro/', 'unknown'),
    (8145, 'Sweet William', 'brandsSweetWilliam', '/brands/SweetWilliam/', 'unknown'),
    (8146, 'White Magic', 'brandsWhiteMagic', '/brands/WhiteMagic/', 'unknown'),
    (8148, 'Bioplus', 'brandsBioplus', '/brands/Bioplus/', 'unknown'),
    (8209, 'Aloe Vera of Australia', 'brandsAloeVeraofAustralia', '/brands/AloeVeraofAustralia/', 'unknown'),
    (8210, 'AromaStick', 'brandsAromaStick', '/brands/AromaStick/', 'unknown'),
    (8211, 'Allan K Suttons', 'brandsAllanKSuttons', '/brands/AllanKSuttons/', 'unknown'),
    (8219, 'Byron Bay Macadamia Muesli', 'brandsByronBayMacadamiaMuesli', '/brands/ByronBayMacadamiaMuesli/', 'unknown'),
    (8220, 'GevityRX', 'brandsGevityRX', '/brands/GevityRX/', 'unknown'),
    (8223, 'The Broth Sisters', 'brandsTheBrothSisters', '/brands/TheBrothSisters/', 'unknown'),
    (8225, 'Cocolife', 'brandsCocolife', '/brands/Cocolife/', 'unknown'),
    (8226, 'Complete Natural Remedies', 'brandsCompleteNaturalRemedies', '/brands/CompleteNaturalRemedies/', 'unknown'),
    (8227, 'Carwari Organic', 'brandsCarwariOrganic', '/brands/CarwariOrganic/', 'unknown'),
    (8228, 'Earths Purities', 'brandsEarthsPurities', '/brands/EarthsPurities/', 'unknown'),
    (8233, 'Fire Tonic', 'brandsFireTonic', '/brands/FireTonic/', 'unknown'),
    (8234, 'Four Leaf', 'brandsFourLeaf', '/brands/FourLeaf/', 'unknown'),
    (8235, 'Foda', 'brandsFoda', '/brands/Foda/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (8243, 'Frequency H2O', 'brandsFrequencyH-O', '/brands/FrequencyH-O/', 'unknown'),
    (8244, 'Golden Ghee Co', 'brandsGoldenGheeCo', '/brands/GoldenGheeCo/', 'unknown'),
    (8328, 'Happy Turtle', 'brandsHappyTurtle', '/brands/HappyTurtle/', 'unknown'),
    (8337, 'Smooze Fruit Ice', 'brandsSmoozeFruitIce', '/brands/SmoozeFruitIce/', 'unknown'),
    (8352, 'Naked Paleo', 'brandsNakedPaleo', '/brands/NakedPaleo/', 'unknown'),
    (8355, 'Organic Oat Slice', 'brandsOrganicOatSlice', '/brands/OrganicOatSlice/', 'unknown'),
    (8356, 'Wild Herbal', 'brandsWildHerbal', '/brands/WildHerbal/', 'unknown'),
    (8357, 'Buontempo', 'brandsBuontempo', '/brands/Buontempo/', 'unknown'),
    (8358, 'Piranha', 'brandsPiranha', '/brands/Piranha/', 'unknown'),
    (8375, 'Sugarwrap', 'sugarwrap', '/sugarwrap/', 'unknown'),
    (8383, 'Turban Chopsticks', 'turban-chopsticks', '/turban-chopsticks/', 'unknown'),
    (8392, 'Sunray', 'brandsSunray', '/brands/Sunray/', 'unknown'),
    (8395, 'Tiger Balm', 'brandsTigerBalm', '/brands/TigerBalm/', 'unknown'),
    (8400, 'Tonik Plant', 'brandsTonikPlant', '/brands/TonikPlant/', 'unknown'),
    (8401, 'Tri Natural', 'brandsTriNatural', '/brands/TriNatural/', 'unknown'),
    (8402, 'Tsuno', 'brandsTsuno', '/brands/Tsuno/', 'unknown'),
    (8403, 'Veego Bars', 'brandsVeegoBars', '/brands/VeegoBars/', 'unknown'),
    (8404, 'Wallaby', 'brandsWallaby', '/brands/Wallaby/', 'unknown'),
    (8406, 'Charco', 'brandsCharco', '/brands/Charco/', 'unknown'),
    (8407, 'Zeoactiv8', 'brandsZeoActiv-', '/brands/ZeoActiv-/', 'unknown'),
    (8409, 'Your Tea', 'your-tea', '/your-tea/', 'unknown'),
    (8412, 'Jomeis Fine Foods', 'brandsJOMEISFINEFOODS', '/brands/JOMEISFINEFOODS/', 'unknown'),
    (8421, 'Pelvi', 'brandsPELVI', '/brands/PELVI/', 'unknown'),
    (8548, 'Coastal Crunch', 'brandsCOASTALCRUNCH', '/brands/COASTALCRUNCH/', 'unknown'),
    (9262, 'Lakanto', 'lakanto', '/lakanto/', 'unknown'),
    (9281, 'Sow N Sow', 'sow-n-sow', '/sow-n-sow/', 'unknown'),
    (9440, 'Meo', 'brandsMEO', '/brands/MEO/', 'unknown'),
    (9904, 'Herbanica', 'brandsHerbanica', '/brands/Herbanica/', 'unknown'),
    (9906, 'Pandas By Luvme', 'brandsPandasbyLuvme', '/brands/PandasbyLuvme/', 'unknown'),
    (9907, 'Kaeh Women', 'brandsKaehWomen', '/brands/KaehWomen/', 'unknown'),
    (9909, 'Vgood', 'brandsVGood', '/brands/VGood/', 'unknown'),
    (9918, 'Grants Of Australia', 'grants-of-australia', '/grants-of-australia/', 'unknown'),
    (9920, 'The Australian Natural Soap Co', 'brandsTHEAUSTRALIANNATURALSOAPCO', '/brands/THEAUSTRALIANNATURALSOAPCO/', 'unknown'),
    (9921, 'Aztec Secret', 'brandsAZTECSECRET', '/brands/AZTECSECRET/', 'unknown'),
    (9923, 'Buddha Teas', 'brandsBUDDHATEAS', '/brands/BUDDHATEAS/', 'unknown'),
    (9931, 'Dandies', 'brandsDANDIES', '/brands/DANDIES/', 'unknown'),
    (9933, 'Everymite', 'brandsEVERYMITE', '/brands/EVERYMITE/', 'unknown'),
    (9935, 'The Fresh Chai Co', 'brandsTHEFRESHCHAICO', '/brands/THEFRESHCHAICO/', 'unknown'),
    (9937, 'Freshpaper', 'brandsFRESHPAPER', '/brands/FRESHPAPER/', 'unknown'),
    (9938, 'The Goodnight Co', 'brandsTHEGOODNIGHTCO', '/brands/THEGOODNIGHTCO/', 'unknown'),
    (9939, 'Grin', 'brandsGRIN', '/brands/GRIN/', 'unknown'),
    (9941, 'Huskee', 'brandsHUSKEE', '/brands/HUSKEE/', 'unknown'),
    (9943, 'Ministry Of Tea', 'brandsMINISTRYOFTEA', '/brands/MINISTRYOFTEA/', 'unknown'),
    (9944, 'Naked Chocolate Co', 'brandsNAKEDCHOCOLATECO', '/brands/NAKEDCHOCOLATECO/', 'unknown'),
    (9945, 'Nelson Naturals', 'brandsNELSONNATURALS', '/brands/NELSONNATURALS/', 'unknown'),
    (9948, 'Radico', 'brandsRADICO', '/brands/RADICO/', 'unknown'),
    (9950, 'Surfmud', 'brandsSURFMUD', '/brands/SURFMUD/', 'unknown'),
    (9951, 'Sol Organics', 'brandsSOLORGANICS', '/brands/SOLORGANICS/', 'unknown'),
    (9959, 'Tj Clark', 'brandsTJCLARK', '/brands/TJCLARK/', 'unknown'),
    (9960, 'Urban Greens', 'brandsURBANGREENS', '/brands/URBANGREENS/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (9961, 'Vitawerx', 'brandsVITAWERX', '/brands/VITAWERX/', 'unknown'),
    (9962, 'Very Vanilla', 'brandsVERYVANILLA', '/brands/VERYVANILLA/', 'unknown'),
    (9963, 'Zero Slim & Healthy', 'brandsZEROSLIM-HEALTHY', '/brands/ZEROSLIM-HEALTHY/', 'unknown'),
    (9981, 'Harmony''s Ear Candles', 'brandsHarmonysEarCandles', '/brands/HarmonysEarCandles/', 'unknown'),
    (9985, 'Clinical Extracts', 'brandsCLINICALEXTRACTS', '/brands/CLINICALEXTRACTS/', 'unknown'),
    (9987, 'Euclove', 'brandsEUCLOVE', '/brands/EUCLOVE/', 'unknown'),
    (9988, 'Free Spirit', 'brandsFreeSpirit', '/brands/FreeSpirit/', 'unknown'),
    (9989, 'The Natural Edge', 'brandsTheNaturalEdge', '/brands/TheNaturalEdge/', 'unknown'),
    (9993, '180 Cakes', 'brandscakes', '/brands/cakes/', 'unknown'),
    (9994, 'Ocean Kissed By Locako', 'brandsOceanKissedByLocako', '/brands/OceanKissedByLocako/', 'unknown'),
    (9995, 'Paleo Hero', 'brandsPaleoHero', '/brands/PaleoHero/', 'unknown'),
    (9996, 'Untamed Health', 'brandsUntamedHealth', '/brands/UntamedHealth/', 'unknown'),
    (10011, 'Summer Salt Body', 'brandsSummerSaltBody', '/brands/SummerSaltBody/', 'unknown'),
    (10019, 'Sanitiser', 'sanitiser', '/sanitiser/', 'unknown'),
    (10020, 'Wild Juice', 'wild-juice', '/wild-juice/', 'unknown'),
    (10021, 'Disensary & Clinic Items', 'disensary-clinic-items', '/disensary-clinic-items/', 'unknown'),
    (10023, 'Miscellaneous', 'miscellaneous', '/miscellaneous/', 'unknown'),
    (10024, 'Dr V', 'dr-v', '/dr-v/', 'unknown'),
    (10026, 'Natural Fertility', 'natural-fertility', '/natural-fertility/', 'unknown'),
    (10028, 'Corowa Distillery Co', 'corowa-distillery-co-1', '/corowa-distillery-co-1/', 'unknown'),
    (10029, 'Peter Dingle', 'peter-dingle', '/peter-dingle/', 'unknown'),
    (10033, 'Nature''s Goodness', 'natures-goodness', '/natures-goodness/', 'unknown'),
    (10034, 'Australia''s Manuka', 'australias-manuka', '/australias-manuka/', 'unknown'),
    (10035, 'Eco SouLife', 'eco-soulife', '/eco-soulife/', 'unknown'),
    (10037, 'Miessence', 'miessence', '/miessence/', 'unknown'),
    (10038, 'Franjo''s Kitchen', 'franjos-kitchen', '/franjos-kitchen/', 'unknown'),
    (10039, 'Hilde Hemmes Herbal''s', 'hilde-hemmes-herbals', '/hilde-hemmes-herbals/', 'unknown'),
    (10041, 'Shelby''s', 'shelbys', '/shelbys/', 'unknown'),
    (10044, 'dr plotka', 'dr-plotka', '/dr-plotka/', 'unknown'),
    (10046, 'Mama Nose', 'mama-nose', '/mama-nose/', 'unknown'),
    (10047, 'Whole Earth Sea', 'whole-earth-sea', '/whole-earth-sea/', 'unknown'),
    (10048, 'Invisi Shield', 'invisi-shield', '/invisi-shield/', 'unknown'),
    (10050, 'Acacia Aromatherapy', 'acacia-aromatherapy', '/acacia-aromatherapy/', 'unknown'),
    (10051, 'Australian Bush Spices', 'australian-bush-spices', '/australian-bush-spices/', 'unknown'),
    (10053, 'It''s Your Body', 'its-your-body', '/its-your-body/', 'unknown'),
    (10054, 'The DivaCup', 'the-divacup', '/the-divacup/', 'unknown'),
    (10056, 'Byron Body', 'byron-body', '/byron-body/', 'unknown'),
    (10057, 'Biody Organic', 'biody-organic', '/biody-organic/', 'unknown'),
    (10058, 'Exmild', 'exmild', '/exmild/', 'unknown'),
    (10063, 'The Organic Tea Box', 'the-organic-tea-box', '/the-organic-tea-box/', 'unknown'),
    (10064, 'ANC Health Supplements | Buy Organics Online', 'anc', '/anc/', 'unknown'),
    (10065, 'LO-LINE TRAPPIT', 'lo-line-trappit', '/lo-line-trappit/', 'unknown'),
    (10066, 'Red Hill Fresh', 'red-hill-fresh', '/red-hill-fresh/', 'unknown'),
    (10068, 'Edwards & Sons', 'edwards-sons', '/edwards-sons/', 'unknown'),
    (10069, 'BD Fresh', 'bd-fresh', '/bd-fresh/', 'unknown'),
    (10071, 'Organic Growers Group', 'organic-growers-group', '/organic-growers-group/', 'unknown'),
    (10074, 'Bio Dynamic Marketing', 'bio-dynamic-marketing', '/bio-dynamic-marketing/', 'unknown'),
    (10079, 'Mungalli Creek', 'mungalli-creek', '/mungalli-creek/', 'unknown'),
    (10080, 'Symons Organic Dairy Co', 'symons-organic-dairy-co', '/symons-organic-dairy-co/', 'unknown'),
    (10082, 'Eddies Cider', 'eddies-cider', '/eddies-cider/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (10083, 'Pure Harvest', 'pure-harvest', '/pure-harvest/', 'unknown'),
    (10096, 'Marrook Farm', 'marrook-farm', '/marrook-farm/', 'unknown'),
    (10101, 'Amys Kitchen', 'amys-kitchen', '/amys-kitchen/', 'unknown'),
    (10103, 'Australias Own', 'australias-own', '/australias-own/', 'unknown'),
    (10106, 'Earth Source', 'earth-source', '/earth-source/', 'unknown'),
    (10109, 'Siena', 'siena', '/siena/', 'unknown'),
    (10113, 'Primasoy', 'primasoy', '/primasoy/', 'unknown'),
    (10117, 'Dalhouse', 'dalhouse', '/dalhouse/', 'unknown'),
    (10118, 'True Organics', 'true-organics', '/true-organics/', 'unknown'),
    (10131, 'Tallyho', 'tallyho', '/tallyho/', 'unknown'),
    (10132, 'Buy Organics Online', 'buy-organics-online', '/buy-organics-online/', 'unknown'),
    (10134, 'Biopet', 'biopet', '/biopet/', 'unknown'),
    (10135, 'Chaga Health', 'brandschaga-health', '/brands/chaga-health/', 'unknown'),
    (10138, 'Source Pro Active', 'source-pro-active', '/source-pro-active/', 'unknown'),
    (10139, 'Baker Boys', 'baker-boys', '/baker-boys/', 'unknown'),
    (10140, 'Gaia Wholefoods', 'gaia-wholefoods', '/gaia-wholefoods/', 'unknown'),
    (10141, 'Smart Juice', 'smart-juice', '/smart-juice/', 'unknown'),
    (10142, 'Hakubaku', 'hakubaku', '/hakubaku/', 'unknown'),
    (10143, 'Sanitarium', 'sanitarium', '/sanitarium/', 'unknown'),
    (10149, 'Ellkeri', 'ellkeri', '/ellkeri/', 'unknown'),
    (10150, 'Base Soaps', 'base-soaps', '/base-soaps/', 'unknown'),
    (10151, 'Extremely Alive', 'extremely-alive', '/extremely-alive/', 'unknown'),
    (10152, 'Chiron', 'chiron', '/chiron/', 'unknown'),
    (10153, 'Arigato', 'brandsArigato.html', '/brands/Arigato.html', 'unknown'),
    (10156, 'Sprout Organic', 'brandsSproutOrganic.html', '/brands/SproutOrganic.html', 'unknown'),
    (10161, 'Dr Pickles', 'brandsDrPickles.html', '/brands/DrPickles.html', 'unknown'),
    (10163, 'Aqua', 'brandsAqua.html', '/brands/Aqua.html', 'unknown'),
    (10170, 'i am grounded', 'i-am-grounded', '/i-am-grounded/', 'unknown'),
    (10198, 'Creative Nature', 'brandsCreativeNature.html', '/brands/CreativeNature.html', 'unknown'),
    (10200, 'Ecyo', 'brandsEcyo.html', '/brands/Ecyo.html', 'unknown'),
    (10201, 'Little Ethique', 'brandsLittleEthique.html', '/brands/LittleEthique.html', 'unknown'),
    (10202, 'Everyorganics', 'brandsEveryorganics.html', '/brands/Everyorganics.html', 'unknown'),
    (10203, 'Earthwise Nourish', 'brandsEarthwiseNourish.html', '/brands/EarthwiseNourish.html', 'unknown'),
    (10204, 'Fijikava', 'brandsFijikava.html', '/brands/Fijikava.html', 'unknown'),
    (10205, 'Funky Sock Co', 'brandsFunkySockCo.html', '/brands/FunkySockCo.html', 'unknown'),
    (10206, 'Grass Roots', 'brandsGrassRoots.html', '/brands/GrassRoots.html', 'unknown'),
    (10208, 'Health Guru', 'brandsHealthGuru.html', '/brands/HealthGuru.html', 'unknown'),
    (10209, 'Imuni', 'brandsImuni.html', '/brands/Imuni.html', 'unknown'),
    (10210, 'J Luehders', 'brandsJLuehders.html', '/brands/JLuehders.html', 'unknown'),
    (10212, 'Low Carb Life', 'brandsLowCarbLife.html', '/brands/LowCarbLife.html', 'unknown'),
    (10213, 'Mindful Foods', 'brandsMindfulFoods.html', '/brands/MindfulFoods.html', 'unknown'),
    (10214, 'Neem', 'brandsNeem.html', '/brands/Neem.html', 'unknown'),
    (10220, 'Strap', 'brandsStrap.html', '/brands/Strap.html', 'unknown'),
    (10221, 'Porter Green', 'brandsPorterGreen.html', '/brands/PorterGreen.html', 'unknown'),
    (10225, 'Stuff', 'brandsStuff.html', '/brands/Stuff.html', 'unknown'),
    (10226, 'Tooshies', 'brandsTooshies.html', '/brands/Tooshies.html', 'unknown'),
    (10227, 'Organic Goodness', 'brandsOrganicGoodness.html', '/brands/OrganicGoodness.html', 'unknown'),
    (10229, 'Slater Farms', 'slater-farms', '/slater-farms/', 'unknown'),
    (10230, 'Demeter Bio-Dynamic', 'demeter-bio-dynamic', '/demeter-bio-dynamic/', 'unknown'),
    (10231, 'Burrum Biodynamic Farm', 'burrum-biodynamic-farm', '/burrum-biodynamic-farm/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (10232, 'Australian Organic Network', 'australian-organic-network', '/australian-organic-network/', 'unknown'),
    (10236, 'Edwards/VIC', 'edwards-vic', '/edwards-vic/', 'unknown'),
    (10237, 'Aromamist', 'brandsAromamist.html', '/brands/Aromamist.html', 'unknown'),
    (10238, 'The Base Collective', 'brandsTheBaseCollective.html', '/brands/TheBaseCollective.html', 'unknown'),
    (10276, 'Before You Speak', 'brandsBeforeYouSpeak.html', '/brands/BeforeYouSpeak.html', 'unknown'),
    (10339, 'Biogenesis Natural Australia', 'brandsBiogenesisNaturalAustralia.html', '/brands/BiogenesisNaturalAustralia.html', 'unknown'),
    (10340, 'Biostime Supplements', 'brandsBiostimeSupplements.html', '/brands/BiostimeSupplements.html', 'unknown'),
    (10376, 'Brain And Brawn', 'brandsBrainAndBrawn.html', '/brands/BrainAndBrawn.html', 'unknown'),
    (10377, 'Base', 'brandsBase.html', '/brands/Base.html', 'unknown'),
    (10378, 'Cub And Bear Co', 'brandsCubAndBearCo.html', '/brands/CubAndBearCo.html', 'unknown'),
    (10394, 'Dr Plotka''s', 'brandsDrPlotkas.html', '/brands/DrPlotkas.html', 'unknown'),
    (10396, 'Earth 2 Brain', 'brandsEarth-Brain.html', '/brands/Earth-Brain.html', 'unknown'),
    (10400, 'Aotearoad', 'aotearoad', '/aotearoad/', 'unknown'),
    (10401, 'Ultrafoods', 'ultrafoods', '/ultrafoods/', 'unknown'),
    (10750, 'Untamed Pets', 'brandsUntamedPets.html', '/brands/UntamedPets.html', 'unknown'),
    (10751, 'Vital Zing', 'brandsVitalZing.html', '/brands/VitalZing.html', 'unknown'),
    (10753, 'Wotnot Naturals', 'brandsWotnotNaturals.html', '/brands/WotnotNaturals.html', 'unknown'),
    (10757, 'Nature''s Harvest', 'brandsNaturesHarvest.html', '/brands/NaturesHarvest.html', 'unknown'),
    (10758, 'Poweroll', 'brandsPoweroll.html', '/brands/Poweroll.html', 'unknown'),
    (10762, 'Natural Life', 'brandsNaturalLife.html', '/brands/NaturalLife.html', 'unknown'),
    (10763, 'Eden Valley', 'eden-valley', '/eden-valley/', 'unknown'),
    (10765, 'The Organic Papa', 'the-organic-papa', '/the-organic-papa/', 'unknown'),
    (10766, 'apricare', 'apricare', '/apricare/', 'unknown'),
    (10767, 'Byron Bay Bellies', 'byron-bay-bellies', '/byron-bay-bellies/', 'unknown'),
    (10771, 'Australian Natural Soap Co', 'australian-natural-soap-co', '/brands/australian-natural-soap-co/', 'unknown'),
    (10772, 'PLENTY', 'plenty', '/brands/plenty/', 'unknown'),
    (10773, 'BURT''S BEES', 'burt''s-bees', '/brands/burt''s-bees/', 'unknown'),
    (10774, 'Natural Vanilla Company', 'natural-vanilla-company', '/brands/natural-vanilla-company/', 'unknown'),
    (10775, 'Native Vanilla', 'native-vanilla', '/brands/native-vanilla/', 'unknown'),
    (10776, 'Gem', 'gem', '/brands/gem/', 'unknown'),
    (10777, 'Redmond', 'redmond', '/brands/redmond/', 'unknown'),
    (10778, 'Alchemy', 'alchemy', '/brands/alchemy/', 'unknown'),
    (10779, 'Blue Dinosaur', 'blue-dinosaur', '/brands/blue-dinosaur/', 'unknown'),
    (10780, 'Berkelo', 'berkelo', '/brands/berkelo/', 'unknown'),
    (10781, 'Buderim Ginger', 'buderim-ginger', '/brands/buderim-ginger/', 'unknown'),
    (10782, 'Keto Naturals', 'keto-naturals', '/brands/keto-naturals/', 'unknown'),
    (10783, 'Real Naturals', 'real-naturals', '/brands/real-naturals/', 'unknown'),
    (10784, 'Banana Joe', 'banana-joe', '/brands/banana-joe/', 'unknown'),
    (10785, 'YAVA', 'yava', '/brands/yava/', 'unknown'),
    (10786, 'Chuu Nutrition', 'chuu-nutrition', '/brands/chuu-nutrition/', 'unknown'),
    (10787, 'CleanLIFE', 'cleanlife', '/brands/cleanlife/', 'unknown'),
    (10788, 'CLIF', 'clif', '/brands/clif/', 'unknown'),
    (10789, 'Cleaner Days', 'cleaner-days', '/brands/cleaner-days/', 'unknown'),
    (10790, 'Cayenne Nature''s Wonder', 'cayenne-nature''s-wonder', '/brands/cayenne-nature''s-wonder/', 'unknown'),
    (10791, 'Carob Farm', 'carob-farm', '/brands/carob-farm/', 'unknown'),
    (10792, 'Dayly', 'dayly', '/brands/dayly/', 'unknown'),
    (10793, 'DJ&A', 'dj&a', '/brands/dj&a/', 'unknown'),
    (10794, 'Eco Lips', 'eco-lips', '/brands/eco-lips/', 'unknown'),
    (10795, 'Pimp My Salad', 'pimp-my-salad', '/brands/pimp-my-salad/', 'unknown'),
    (10796, 'Pimp My Snack', 'pimp-my-snack', '/brands/pimp-my-snack/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

INSERT INTO seo_brands (bc_brand_id, name, slug, url, content_status) VALUES
    (10797, 'Ecoegg', 'ecoegg', '/brands/ecoegg/', 'unknown'),
    (10798, 'Eumundi Botanicals', 'eumundi-botanicals', '/brands/eumundi-botanicals/', 'unknown'),
    (10799, 'Eden Healthfoods', 'eden-healthfoods', '/brands/eden-healthfoods/', 'unknown'),
    (10800, 'Epic', 'epic', '/brands/epic/', 'unknown'),
    (10801, 'Every Bit Organic', 'every-bit-organic', '/brands/every-bit-organic/', 'unknown'),
    (10802, 'Naturely Nourish', 'naturely-nourish', '/brands/naturely-nourish/', 'unknown'),
    (10803, 'The Fresh Chai Co.', 'the-fresh-chai-co.', '/brands/the-fresh-chai-co./', 'unknown'),
    (10804, 'Faith In Nature', 'faith-in-nature', '/brands/faith-in-nature/', 'unknown'),
    (10805, 'Gaiam', 'gaiam', '/brands/gaiam/', 'unknown'),
    (10806, 'Great Aussie Wipes', 'great-aussie-wipes', '/brands/great-aussie-wipes/', 'unknown'),
    (10807, 'Good Change Store', 'good-change-store', '/brands/good-change-store/', 'unknown'),
    (10808, 'The Gluten Free Food Co.', 'the-gluten-free-food-co.', '/brands/the-gluten-free-food-co./', 'unknown'),
    (10809, 'Good Riddance', 'good-riddance', '/brands/good-riddance/', 'unknown'),
    (10810, 'Heritage Store', 'heritage-store', '/brands/heritage-store/', 'unknown'),
    (10811, 'NFco.', 'nfco.', '/brands/nfco./', 'unknown'),
    (10812, 'The Good Crisp Company', 'the-good-crisp-company', '/brands/the-good-crisp-company/', 'unknown'),
    (10813, 'Infuzions', 'infuzions', '/brands/infuzions/', 'unknown'),
    (10814, 'Leda', 'leda', '/brands/leda/', 'unknown'),
    (10815, 'The Monday Food Co.', 'the-monday-food-co.', '/brands/the-monday-food-co./', 'unknown'),
    (10816, 'Mt. Elephant', 'mt.-elephant', '/brands/mt.-elephant/', 'unknown'),
    (10817, 'Myles Gray', 'myles-gray', '/brands/myles-gray/', 'unknown'),
    (10818, 'Nimbus', 'nimbus', '/brands/nimbus/', 'unknown'),
    (10819, 'Nutri-Leaf', 'nutri-leaf', '/brands/nutri-leaf/', 'unknown'),
    (10820, 'Niulife', 'niulife', '/brands/niulife/', 'unknown'),
    (10821, 'Naturally Good', 'naturally-good', '/brands/naturally-good/', 'unknown'),
    (10822, 'Nature''s Help', 'nature''s-help', '/brands/nature''s-help/', 'unknown'),
    (10823, 'Nutry Nuts', 'nutry-nuts', '/brands/nutry-nuts/', 'unknown'),
    (10824, 'People4Ocean', 'people4ocean', '/brands/people4ocean/', 'unknown'),
    (10825, 'Ocean''s Halo', 'ocean''s-halo', '/brands/ocean''s-halo/', 'unknown'),
    (10826, 'Ora Health', 'ora-health', '/brands/ora-health/', 'unknown'),
    (10827, 'Orgaid', 'orgaid', '/brands/orgaid/', 'unknown'),
    (10828, 'Next Generation Pet Foods', 'next-generation-pet-foods', '/brands/next-generation-pet-foods/', 'unknown'),
    (10829, 'Purely Potato', 'purely-potato', '/brands/purely-potato/', 'unknown'),
    (10830, 'Epzen', 'epzen', '/brands/epzen/', 'unknown'),
    (10831, 'Ritua', 'ritua', '/brands/ritua/', 'unknown'),
    (10832, 'Sourdough Mumma', 'sourdough-mumma', '/brands/sourdough-mumma/', 'unknown'),
    (10833, 'Sodii', 'sodii', '/brands/sodii/', 'unknown'),
    (10834, 'Sow ''n Sow', 'sow-''n-sow', '/brands/sow-''n-sow/', 'unknown'),
    (10835, 'Smart Protein Bar', 'smart-protein-bar', '/brands/smart-protein-bar/', 'unknown'),
    (10836, 'Stuff That Matters', 'stuff-that-matters', '/brands/stuff-that-matters/', 'unknown'),
    (10837, 'Switch Nutrition', 'switch-nutrition', '/brands/switch-nutrition/', 'unknown'),
    (10838, 'The Betta Company', 'the-betta-company', '/brands/the-betta-company/', 'unknown'),
    (10839, 'Thrive Tallow', 'thrive-tallow', '/brands/thrive-tallow/', 'unknown'),
    (10840, 'Dr. Organic', 'dr.-organic', '/brands/dr.-organic/', 'unknown')
ON CONFLICT (bc_brand_id) DO NOTHING;

